# Generated by Django 4.2.6 on 2023-11-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
